### ISSUE TITLE
Rate per Hour of 0

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#155] opened 2022-07-11 20:07 UTC
Please allow rate per hour of 0 (i.e. ground stop)

(System allows this, but the note below it says it's not)

**Comment by NelisV** [comment] 2022-07-11 20:13
to me that would be a duplicate of prohibit.

**Comment by KHardern** [comment] 2022-07-11 20:40
Agreed it's a duplicate, however with our ability to have 'nested' prohibit rules it becomes quite confusing when a prohibit is made and people have to go looking for mandatory routes.

It's unambiguous to issue a ground stop as rate per hour of 0 and therefore I figure we should change it over to this method. Apologies, I meant to discuss this at the meeting.

**Closed** 2022-07-11 20:50 UTC
Labels: question
